###
POST http://localhost:3000/api/v1/products HTTP/1.1
Content-Type: application/json

{
  "title":"Pokemon Yellow Version - Special Pikachu Edition (Renewed)",
  "description":"The plot of Yellow is very similar to that of the Japanese Red and Green and Japanese Blue...",
  "price":135,
  "Available_Units":5,
  "category":"Video Games"
}


###
GET http://localhost:3000/v1/products HTTP/1.1


###
GET http://localhost:3000/v1/products/644d147d51c08e90872cb030 HTTP/1.1

###
PUT http://localhost:3000/v1/products/644d147d51c08e90872cb030 HTTP/1.1
Content-Type: application/json

{
  "title":"Pokemon - Diamond Version (Renewed)",
  "description":"More elaborate Pokemon Contests. Players can use the accessories and dress up their Pokemon.",
  "price":280,
  "Available_Units":20,
  "category":"Video Games"
}

###
DELETE http://localhost:3000/v1/products/64489a5f8475e617ba3a0779 HTTP/1.1