###
POST http://localhost:3000/api/v1/products HTTP/1.1
Content-Type: application/json

{
  "title":"Pokemon HeartGold Version - Limited Edition - Nintendo DS",
  "description":"Prepare for thrilling new adventures as Legendary Pokémon awaken!.",
  "price":200,
  "Available_Units":15,
  "category":"Video Games"
}


###
GET http://localhost:3000/api/v1/products HTTP/1.1


###
GET http://localhost:3000/api/v1/products/64488f60316848c64837dced HTTP/1.1

###
PUT http://localhost:3000/api/v1/products/64488f60316848c64837dced HTTP/1.1
Content-Type: application/json

{
  "title":"Pokemon - Diamond Version (Renewed)",
  "description":"More elaborate Pokemon Contests. Players can use the accessories and dress up their Pokemon.",
  "price":280,
  "Available_Units":20,
  "category":"Video Games"
}

###
DELETE http://localhost:3000/api/v1/products/64488f60316848c64837dced HTTP/1.1